"""Geometry helpers: distances, trajectory sampling, proximity graph.

Trajectory expressions accept ``t`` and the standard NumPy namespace as
``np``. Evaluation uses :func:`eval` with a *restricted* namespace; the
expressions come from the trusted JSON instance which is generated by the
SimLab tooling, not from untrusted user input. We still guard against
unexpected builtins by passing ``{"__builtins__": {}}``.
"""

from __future__ import annotations

import math
from typing import Iterable

import numpy as np

from p2_population_estimator.models import (
    MobileNode,
    P2Problem,
    Point,
)


# ---------------------------------------------------------------------------
# Distance / geometry
# ---------------------------------------------------------------------------
def euclidean(a: Point, b: Point) -> float:
    return math.hypot(a.x - b.x, a.y - b.y)


def pairwise_distances(points: list[Point]) -> np.ndarray:
    arr = np.array([[p.x, p.y] for p in points], dtype=float)
    dx = arr[:, 0:1] - arr[:, 0:1].T
    dy = arr[:, 1:2] - arr[:, 1:2].T
    return np.hypot(dx, dy)


# ---------------------------------------------------------------------------
# Trajectory evaluation
# ---------------------------------------------------------------------------
_SAFE_NS = {
    "np": np,
    "math": math,
    "sin": math.sin, "cos": math.cos, "tan": math.tan,
    "exp": math.exp, "log": math.log, "sqrt": math.sqrt,
    "pi": math.pi, "e": math.e,
    "abs": abs, "min": min, "max": max,
}


def _eval_expr(expr: str, t: float) -> float:
    """Evaluate a single ``x(t)`` / ``y(t)`` expression. Restricted namespace."""
    try:
        return float(eval(  # noqa: S307 - trusted input; namespace is sandboxed
            expr, {"__builtins__": {}}, {**_SAFE_NS, "t": t}
        ))
    except Exception as exc:
        raise ValueError(f"Failed to evaluate trajectory expression {expr!r} at t={t}: {exc}") from exc


def sample_trajectory(node: MobileNode, num_samples: int) -> list[Point]:
    """Sample ``num_samples`` points along the node's trajectory.

    We use a coarse uniform parametrisation: each segment gets a roughly equal
    share of samples, and within a segment ``t`` is mapped uniformly to
    [0, 1]. This is sufficient for structural surrogate metrics; precise time
    integration is out of scope here.
    """
    if num_samples <= 0:
        return []
    segments = node.path_segments
    if not segments:
        return []

    n_segs = len(segments)
    # Distribute samples across segments
    per_seg_base = num_samples // n_segs
    remainder = num_samples - per_seg_base * n_segs
    per_seg = [per_seg_base + (1 if i < remainder else 0) for i in range(n_segs)]

    out: list[Point] = []
    for seg_idx, (sx, sy) in enumerate(segments):
        n_here = per_seg[seg_idx]
        if n_here <= 0:
            continue
        # Endpoints inclusive for the first and last sample of each segment to
        # avoid losing the transition points.
        for k in range(n_here):
            t = k / max(n_here - 1, 1) if n_here > 1 else 0.5
            x = _eval_expr(sx, t)
            y = _eval_expr(sy, t)
            out.append(Point(x, y))
    return out


def sample_all_mobiles(
    problem: P2Problem, num_samples: int
) -> list[list[Point]]:
    """Return ``[trajectory_m for m in mobile_nodes]``."""
    return [sample_trajectory(m, num_samples) for m in problem.mobile_nodes]


# ---------------------------------------------------------------------------
# Proximity / connectivity graph
# ---------------------------------------------------------------------------
def build_relay_graph(
    candidates: list[Point],
    sink: Point,
    radius: float,
    selected: Iterable[int],
) -> dict[int, list[int]]:
    """Adjacency list over selected relays + sink.

    Node ids:
      - ``-1`` denotes the sink
      - integers >= 0 are indices into ``candidates``

    Edges exist when Euclidean distance <= ``radius``.
    """
    sel = sorted(set(selected))
    adj: dict[int, list[int]] = {-1: []}
    for j in sel:
        adj[j] = []

    # sink <-> relays
    for j in sel:
        if euclidean(candidates[j], sink) <= radius:
            adj[-1].append(j)
            adj[j].append(-1)

    # relay <-> relay
    for i, ji in enumerate(sel):
        for jj in sel[i + 1:]:
            if euclidean(candidates[ji], candidates[jj]) <= radius:
                adj[ji].append(jj)
                adj[jj].append(ji)
    return adj


def shortest_hops_to_sink(adj: dict[int, list[int]]) -> dict[int, int]:
    """BFS from the sink (-1). Returns hop-count map; missing keys = unreachable."""
    if -1 not in adj:
        return {}
    visited: dict[int, int] = {-1: 0}
    frontier: list[int] = [-1]
    while frontier:
        nxt: list[int] = []
        for node in frontier:
            for n in adj[node]:
                if n not in visited:
                    visited[n] = visited[node] + 1
                    nxt.append(n)
        frontier = nxt
    return visited


def mobile_reachable_via_relay(
    mobile_pos: Point,
    candidates: list[Point],
    sink: Point,
    radius: float,
    hops_from_sink: dict[int, int],
) -> tuple[bool, int, float]:
    """Check whether ``mobile_pos`` can reach the sink given precomputed hop
    distances over the selected relays.

    Returns (reachable, hop_count_including_mobile, min_distance_to_anchor).
    """
    # Direct to sink?
    d_sink = euclidean(mobile_pos, sink)
    best_hops: int | None = None
    best_dist = d_sink
    if d_sink <= radius:
        best_hops = 1  # one hop: mobile -> sink

    for j, h in hops_from_sink.items():
        if j == -1:
            continue
        d = euclidean(mobile_pos, candidates[j])
        if d < best_dist:
            best_dist = d
        if d <= radius:
            cand_hops = h + 1  # one extra hop: mobile -> relay
            if best_hops is None or cand_hops < best_hops:
                best_hops = cand_hops

    if best_hops is None:
        return (False, 0, best_dist)
    return (True, best_hops, best_dist)
